version: '3.1'

services:

  adsync:
    image: vavere/redmine_adsync:1.1.1
    restart: always
    depends_on:
    - app
    networks:
    - back
    volumes:
    - ./adsync.json:/app/config/production.json

  app:
    image: vavere/redmine:3.4.5-2
    restart: always
    depends_on:
    - db
    - cache
    environment:
    - DB_ADAPTER=postgresql
    - DB_HOST=db
    - DB_PORT=5432
    - DB_NAME=${DB_USER}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}

    - MEMCACHE_HOST=cache
    - MEMCACHE_PORT=11211

    - REDMINE_SECRET_TOKEN=${REDMINE_SECRET_TOKEN}
    - REDMINE_HTTPS=${REDMINE_HTTPS}

    - SMTP_ENABLED=${SMTP_ENABLED}
    - SMTP_METHOD=smtp
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_STARTTLS=false
    - SMTP_TLS=false

    - REDMINE_BACKUP_SCHEDULE=daily
    - REDMINE_BACKUP_EXPIRY=2592000

    - REDMINE_REMINDER_EMAILS=true
    ports:
    - 80:80
    - 443:443
    networks:
    - back
    volumes:
    - ./app:/home/redmine/data
    - ./log:/var/log/redmine

  cache:
    image: memcached:alpine
    restart: always
    networks:
    - back

  db:
    image: postgres:alpine
    restart: always
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}
    networks:
    - back
    volumes:
      - data:/var/lib/postgresql/data

networks:
  back:

volumes:
  data:
